# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt  # Si vous avez des dépendances
  sphinx:
  configuration: docs/conf.py  # Chemin vers votre fichier conf.py (pour Sphinx)